# Generated by Django 4.1.5 on 2023-01-16 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='shinhan_product',
        ),
    ]
