# Generated by Django 4.1.5 on 2023-01-19 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='product',
            new_name='aaaa',
        ),
    ]
